### ISSUE TITLE
idea: map delsys like a Trans Modulator / Receiver Remultiplexer

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#221]
I have a hardware SAT>IP client (Panasonic Viera) where you have to decide the delsys dvb-s or dvb-c and you cannot have both at the same time. But I like to map a "cable" DVB-C tuner to a satellite position or transponders of a satellite position. So I like to ask if it's possible to  do a "mapping"  from one "tuner type" to "another type". For example, map a entire DVB-C mux with all channels to a satellite transponder. Obviously, the parameters from the client related to tuner options (polarization, modulation, etc.) needs to be masked/translated, but the only relevant value is the frequency, because it should be easy to map one DVB-T/C mux list to a satellite transponder list.

Example:

Map DVB-T_Europe to DVB-S_3592 (Thor & Intelsat 0.8°W)

12=474000,8 --> 12=11229,H,24500,78,1

So when the client ask for "src=1&fe=1&msys=dvbs&freq=11229&pol=h&sr=24500..." the server process "src=1&fe=1&msys=dvbt&freq=474&bw=8..."

would this be feasible, or is anyone else interested in such feature?

**Comment by lars18th** [comment]
Hi @9000h ,

I also agree for "Tune Space Remapping". I do some work on this (with external proxy remapping). However, I suggest to include it directly in minisatip if Catalin likes it! ;)

The main concern is how to specify the mapping, as you pointed.
I suggest to use this format as it's very close to standard LinuxTV files:

```
# Comment:
# Mapping DVB-T Channels to Intelsat 1002 @ 1.0W  (you tune DVB-T as 1.0W DVB-S)
#   TARGET @ REQUEST
#  [Any RTSP command with 'REQUEST' is replaced with 'TARGET']

T 506000000 8MHz 2/3 NONE QAM16 8k 1/8 NONE # CH25
@
S 4175000 V 28000000 AUTO

T 522000000 8MHz 2/3 NONE QAM16 8k 1/8 NONE # CH27
@
S 4180000 H 21050000 AUTO

C 394000000 6900000 NONE QAM64 @ S 11093000 H 19191000 7/8
```

As you can see, you can put variations and different subformats. Also S2, T2 and C2 can be supported. You can assing that file to specific target adapters like this:

$ minisatip -a 1:0:0 -e 1 --remap 0:/minisatip/remap-file

As you can see it can be easy to describe.

Another point is the link between requested adapters and target adapters. My suggestion is make as simple as possible. Then the remapping to assigned to only one adapter, and all remappings are internally processed to target adapters. This opens the option of use multiple space tunning spaces in the same remapping. And you can map anything in one adapter. But the problem here is when you like to map a virtual adapter. For example, you have two adapters, DVB-T and DVB-C, and you like to map to DVB-S2 as it's more common. But if you don't have any DVB-S device, how to remmap it? From my point of view this implies, for simplicity, to implement the option of "virtual" adapters. In general they are only advertised devices with 'zero' tuners (any tunning command to them fails). Then they can be remapped very easy.

Catalin, what you think?

**Comment by catalinii** [comment]
I think the simpliest way is to translate the URL ... (freq=12466&.... In freq=456&... ) and use the translated URL for tuning.

There is -a where u can specify DVB-S2 adapters if u dont have any...so the TV uses that adapter to tune and the tuning is done by the existing adapters.

**Comment by lars18th** [comment]
Hi @catalinii ,

> I think the simpliest way is to translate the URL ... (freq=12466&.... In freq=456&... )
> and use the translated URL for tuning.

Yes, make the mapping using URL is the simple mode. However, You need to determine if:

a) You like to map an entire adapter, or only some frequencies. If you select an entire adapter (more simple) then I recommend to map something (DVB-T or DVB-C) to some orbital position with a DVB-S/S2 using the "src" parameter.

b) You need to also "remap" the other parameters when translate to another tunning space (pol,sr,...). I suggest to use some decription file instead of  one fixed translation. But be free to implement what you like! :)

> There is -a where u can specify DVB-S2 adapters if u dont have any...
> so the TV uses that adapter to tune and the tuning is done by the existing adapters.

Yes, but this don't create the "virtual adapter". Then, how to assign some mapping to this adapter? I suggest to add support for dummy adapters. They return false to all tunning commands, but the can advertise the tuner.

What you think?

**Comment by catalinii** [comment]
Well mapping will leave one problem.

NIT will contain invalid information so network scanning will not work.

If u make NIT work (replacing tuning parameters) it will became a mess to specify manually...so only mapping the Frequency automatically will work (newfreq=f(oldfreq))

When everything is discussed it can be decided how to implement it...

**Comment by lars18th** [comment]
Hi @catalinii ,

No, NIT info don't disturbs any scanning process! NIT data is only "informative" info, not used by most of the devices. Moreover, several Transponders and Terrestrial MUXes have incomplete or erroneous NIT info. They are used only for a very specific scenarios (for instance, when you like to change some frequency to another in the broadcast network).

I have done several (large) number of tests with remappings, and it works with all clients. The NIT data is practically discarded. So, please, don't worry about it! Belive me!

Related to the discussion: What you think is more feasible?

a) Fixed map from DVB-T & DVB-C frequencies to DVB-S2 in one orbital position.
b) Mapping based on files with tuning-space-freq -> tuning-space-freq.
c) Remapping based on URL rewrite (with regular expression replaces)

I like to help on this because I'm very interested on it. ;)

**Comment by catalinii** [comment]
b) Thinking about it probably the best way is to translate frequencies using some type of formula, to convert from dvb-s to dvb-c

About NIT I meant that your TV might read NIT in order to determine the other transponders that contains channels.

a) and c) I think are the less flexible possibilities...

**Comment by lars18th** [comment]
Hi @catalinii ,

All my tests using "translation" of TS don't creates any troubles based on NIT. Please, don't care about it at all! :)

Related to the best option for mapping: I have two ideas. First can be the first step (more simple to implement), and the second is the advanced mode.

Here are the basis about the first idea:

* The rewrite mode maps DVB-T/DVB-C only to DVB-S.
* All translations are done at "URL request" level.
* Fixed formulas are used for the transformation.
* Mapping are described using a new command line parameter.

Here the discussion about this mapping:

- When some client request "?msys=dvbs&fe=4freq=" then the URL is rewrited to "?msys=dvbt&freq=" or "?msys=dvbc&freq=" based on rules about the target tuner.
- Parameters related to the transponder ("sr", "fec", etc.) will be discarded; "pids" are untouched.
- The main formula is (dvbt/c used MHz, dvbs KHz):
 - when mapping to dvbt -->freq'=(freq*1000)-500000
 - when mapping to dvbc -->freq'=(freq*1000)-300000
- Parameters for dvbt/c tuning are all "auto" except "freq".
- Mapping is described as: "-m 1:2,4" This indicates that the "tuner 1" is mapped to "tuner 2" at frontend 4 (dish 4). This implies that "tuner 1" exists and it's dvb-t or dvb-c, and "tuner 2" exists and it's dvb-s.
- You need to add the option to instantiate "virtual" tuners, as for example, if you have only one dvb-t tuner and like to present it as a dvb-s tuner, you need to have to use two tuners.

What you think?

**Comment by lars18th** [comment]
Hi @catalinii ,

I rewrite my suggestion to be more simple. Please, let me know if you agree:

* Remmaping will do *only* frequency translations. Moreover, target can be only DVB-T as it can operate with all parameters as "auto" and you can discard all of the original parameters (except "pids").

So, the final suggestion is: if you request any dvb-s/s2/c/2 tunning, but if you set the mapping mode, then the original frequency will be translated to dvb-t.

Here one example:

```
$ minisatip -map 10729:474;210:490
```

So this instructs for: When you request to tune dvb-s 10729MHz, rewrite the request for tunning dvb-t 474MHz (ch21,auto); also when tune dvb-c 210 rewrite to dvb-t 490 (ch23,auto).

The advantage of this mode is: the code of minisatip only needs to "remap" when receive the tunning request, and after this change (only targeting the text of the request) the code continues to be the same. So if no dvb-t available then the tunning fails. No more, no less!

What you think?

**Comment by catalinii** [comment]
Hi,

My thought is to make this as general as possible. And I would want ideally automatic (formula based mapping).


The command line needs to be simple enough to be understood.

Something like -m 2:dvbs

Which would mean map dvbs to adapter 2 (translate dvb-s to dvb-c - because adapter 2 is dvb-c).

Manual manipulation leaves the possibility of creating code that might be useless in the future...

**Comment by lars18th** [comment]
Hi @catalinii ,

I absolutly agree with you that is relevant to minimize the user error!
However, your suggestion has some limitations:

1) This doesn't have the option to "mixing" different delsys.
2) A fixed formula mapping hardcoded in the code can be valid today, but invalid in the future.

So, I agree to be simple and clear. Here another idea:

```
$ minisatip -m dvbs:all:dvbc
$ minisatip -m dvbs:10729-10891:dvbt
$ minisatip -m dvbt:474-490,786-858:dvbs
$ minisatip -m dvbs:all:dvbc;dvbt:all:dvbc
```

The behaviours of examples are (I hope very obvious):

1) map all requested freq. with dvbs to dvbc.
2) map only freq. of dvbs in the range to dvbc freq.
3) idem to 2 with more than one range.
4) two mappings: all dvbs and dvbt to dvbc.

With this solution is ease to process the simple case (full mapping: i.e. dvbs:all:dvbc). Also a more complex case with ranges (this enable "mixing mappings"). Moreover, you don't need to specify the target adapter, as it can be irrelevant... you like to map frequencies not adapters. The mapping is done rewriting the request, so the code can handle the new target if the adapter exists or not. Also, this is compatible with master/slave adapters. So, please, don't try to map adapters.

Finally, the only missing question is the "mapping formula". If you agree to continue in the way discussed here, I'll try to find a formula for it.

What is your opinion?

**Comment by 9000h** [comment]
there is a project on github here which does this as proxy with mapping https://github.com/jfont555/satip_proxy_tool

**Comment by lars18th** [comment]
Hi @9000h ,

Please, close this ancient issue. Another SAT>IP opensource server SATPI has this functionality:  https://github.com/Barracuda09/SATPI

Regards.

**Comment by 9000h** [comment]
would be still nice to have it in minisatip

**Comment by lars18th** [comment]
> would be still nice to have it in minisatip

Yes, but as minisatip has `satipc` functionality, it's quite simple to use it as frontend and SATPI as backend with the translation functionality. Try it!
