### ISSUE TITLE
RFE: Transcoding

### ISSUE THREAD

**Issue by J4nsen** [catalinii/minisatip#238]
Hi,
would it be possible to add a transcoding option to convert mpeg2 to h264 or limit the bitrate of an existing h264 video stream?

I would like to use a VDR at the city where I currently live (I can only receive DVB-T here). My idea is to create a VPN between me and my old home, where minisatip is already running. My initial setup works fine, but the upload of my old home is to small.

Is this even possible/conform with the DVB/satip standard? 
Would this fit into the idea of minisatip?

**Comment by catalinii** [comment]
Hi,

I think the only way would be to transcode into h264 or h265. But you would need a powerfull enough box to be able to achieve it.

From my perspective it can be done using ffmpeg libraries.

Having said that, satip protocol does not specify anything about the transcoding. Additionally there are tools that are already doing it, like tvheadend.

If there will be alot of users wanting it, I can try to implement it.

**Comment by lars18th** [comment]
Hi,

My suggestion is not implement this... directly. It will complicates the code a lot. However, a simple alternative exists:

If you use the HTTP client mode of minisatip, then you can use a "transcode proxy" for a remote playing. In this case, it's easy to install a simple Streaming Server that can implement the service (a lot exists!). The starting point can be a .M3U pointing to your minisatip server using HTTP calls. You can use this file for your transconding server.

As an example, you can try TVHeadend.

Try it!

**Comment by catalinii** [comment]
I guess we can leave this open if someone else is interested in this they can comment here.

The other possibility is implementing it in hardware for ARMv7 or ARMv8 that has a hardware encoder (like Amlogic, Samsung, HiSillicon).

Thanks

**Comment by UKenGB** [comment]
I have just asked about this on the forum as I need to transcode the mp2 audio stream (from the tuner) to mp3 as many players cannot handle mp2 format audio.

Would appreciate it if lars18th could elaborate on his 'transcode proxy' idea. I was thinking of using ffmpeg between minisatip and icecast, but the trouble is going to be starting and stopping minisatip when listeners connect and then disconnect from Icecast.

It would be ideal if minisatip was able to transcode (using external ffmpeg probably) as that process would be controllable by minisatip so tuners still unused when no listerners.

**Comment by lars18th** [comment]
Hi @UKenGB ,

Before commenting something, just one point: Why you say that many players cannot handle mp2 format audio? The MPEG-1 Audio Layer II (real name of the "mp2" codec) is the **ONLY** universal audio codec supported by the 100% of the TV Players around the world. So it's impossible to found a video player not supporting such audio codec. In fact, the "mp3" is not used for TV.

After that, regarding the "transcode proxy" you only need to search for a "homemade IPTV server". Some of these tools can provide the transcoding functionality you want. Using minisatip you can create a M3U file with the programs of your interest. And then the selected transcoding tool can use such M3U list as the input.

Futhermore, to achieve your goal you don't need at all to "start and stop minisatip". You just need to run it. And create a M3U file with something like (this is just one "fake" example):
```
#EXTINF:-1,CHANNEL-1
http://minisatip:8080/?src=1&freq=12345&pol=v&msys=dvbs2&sr=22000&pids=0,16,17,18,20,21,16,17,18,20,21,100,101,102
#EXTINF:-1,CHANNEL-2
http://minisatip:8080/?src=1&freq=12345&pol=v&msys=dvbs2&sr=22000&pids=0,16,17,18,20,21,16,17,18,20,21,200,201,202
```
You can test your M3U file using for example the good known VideoLAN (VLC). The tuner will be in use only when some client request for a channel. In any other case the tuner will be off.

If this is not your case, please describe with a more detail your environment.
Regards.

**Comment by UKenGB** [comment]
Ah yes, I can see I wasn’t entirely clear about a number of things.

I am currently only dealing with satellite RADIO broadcast via FreeSAT in UK. MP2 is of course an audio codec and MP3 also, not video at all. It is Internet radio players that mostly seem to not support MP2. It works perfectly with VLC and also Tune-In radio (iOS app), but both the radio players I actually want to use do NOT support MP2 and in fact I’ve not found another that does.

So I thought of an intermediate transcoding process using ffmpeg that could pull the MP2 stream from minisatip and send an MP3 stream to Icecast for distribution to multiple listeners (instead of minisatip providing that). This is certainly possible, but introduces what are currently insurmountable problems.

When I mentioned starting and stopping minisatip, I meant starting and stopping the stream. The minisatip process would always be running on the server (is already in fact), but it needs to stop streaming when there are no more listeners. Apart from wanting to not waste CPU energy on streaming data through the tuners, transcoding and pushing to Icecast when not required, it is crucial that when there are no radio listeners, minisatip releases that tuner for other uses, whether that be a different radio listener, or indeed for TV usage.

So the entire process has to stop when there are no listeners and while minisatip of course does this on its own, placing an intermediate transcoding process screws it all up. As long as that process is pulling the stream, minisatip will keep streaming from that tuner and only stop and release the tuner when the transcoding process stops. But that transcoding process does not know when to start and stop as it has no concept of ‘listeners’. I can create a script that does the transcoding, for each station to which I might want to listen, but I have no way to automatically start and stop it when the first listener connects, or the last listener disconnects respectively.

This is the problem. Both Icecast and minisatip know when there are listeners and start/stop streaming as appropriate, but any intermediate transcoding process gets in the way.

I’d rather not have to use Icecast for this at all, as it duplicates what minisatip already does, i.e. streams on demand a single source to multiple listeners, so I really want minisatip to be able to actually transcode the stream. I don’t think it needs to do this itself, but to provide some configuration options that makes it send the output stream via an external process (ffmpeg being the obvious choice). In this way, since minisatip knows when listeners connect and disconnect and hence when to stream and when to stop, it would be able to run the transcoding on demand also. There would be no outward difference to the operation of minisatip, just that the output stream would be a different format and by the use of ffmpeg in this way, minisatip needs not concern itself with the details of the required stream. That would depend entirely on the user’s configuration of the ffmpeg options that would need to be specified within the minisatip options I guess.

I hate the fact that there is this problem as minisatip does such a great job and it’s merely the inability of other software that causes the issue. But the best solution has to come from minisatip as that is the only process that knows when there are any listeners. However with this additional functionality, it becomes the perfect server to stream broadcast audio onto the network in any format known to man (and for which ffmpeg has been compiled of course).


Ken  G i l l e t t

_/_/_/_/_/_/_/_/

**Comment by lars18th** [comment]
Hi @UKenGB ,

Thank you for the explanation. Now it's clear that you want to stream RADIO services, not AV services. Ok.

However, you have an incorrect assumption: it's false that minisatip is the only process that knows when there are listeners. What you need to implement is a PULL REQUEST chain. And now you're experimenting with a PUSH chain. What's the difference? In a PUSH chain the producer will _push_ the data to the next element in the chain (a consumer). However, in a PULL REQUEST chain _every_ element is a consumer and it only request data when it's required. See this diagram:
```
     SAT ------> tuner ------> minisatip ---/HTTP/---> transcoder ---/HTTP/---> clients
```

The key point here is that the client requests to the transcoder. Then this module knows about what needs the client. And it not only transcodes but it requests to minisatip as well. So it's not necessary that minisatip knows _directly_ about clients (it knows indirectly).

Please, compare now with your current environment:

```
     SAT ------> tuner ------> minisatip <---/HTTP/--- icecast ---/HTTP/---> clients
```

The difference here is that icecast is getting full time the stream from minisatip. So here is where you found a problem.

After commenting that, I need to say:
- Based on the KISS model it's preferable to not introduce in any way a transcoding support inside minisatip.
- You can implement a clean and efficient environment using the correct architecture.
- What you need is to search for a transcoder with on-demand support.

I hope this helps you.
Regards.

**Comment by UKenGB** [comment]
Yes, you’re absolutely right and I came to the same conclusion, I need an on-demand transcoder. Been puzzling that one for several days without success. You have any suggestions?


Ken  G i l l e t t

_/_/_/_/_/_/_/_/

**Comment by UKenGB** [comment]
Another problem just occurred to me. How could such an on-demand transcoder handle multiple listeners. What we have discussed really only works for a single listener. Additional listeners would each start their own transcode process, all doing the same thing and appallingly inefficient. What is needed is some sort of broadcaster that can handle multiple listeners from just one single input, but which needs to employ the transcoder for that source. Which brings us full circle back to Icecast controlling the transcoder or even better, minisatip as Icecast would just be duplicating what minisatip already does, feed a single source out to multiple listeners.

I understand your desire for KISS, but I cannot get away from the fact that the best solution is for minisatip to provide the transcoding, so the single source (from the tuner) is transcoded (on-demand) and then distributed to each connected listeners. Surely the ability to route the stream via e.g. ffmpeg would not add any huge complexity and the ffmpeg configuration would be up to the user, so minisatip doesn’t need to concern itself with any of that, just pass the user specified options to ffmpeg. If this is not required, users do nothing, no additional configuration to be done. But add some additional options to minisatip and it would be able to stream in any format.

Creating an on-demand transcoder is one level of complexity, but trying to create one that handles multiple ‘listeners’ is many levels more complex and in many ways simply duplicating what Icecast and minisatip already do. So there’d be triple redundancy of code.

The best solution is for minisatip to control the transcoding, i.e. control, not actually perform it as ffmpeg is available to do that.


Ken  G i l l e t t

_/_/_/_/_/_/_/_/

**Comment by lars18th** [comment]
Hi @UKenGB ,

Please, belive me: include a transcoder inside minisatip is:
- Innecessary.
- A lot of effort to achieve it.
- And we don't have any person with sufficient time to spend effort on it.

Perhaps the most positive is to explain why it's completly innecessary:

- You have the wrong assumption that the transcoder is a dumb server. And this is totally erroneous. When two clients request the same resource, the transcoder don't pass another request of the same data. That's a waste of resources. And in fact, any transocding server works in this way. Then what the transcoder has is a list of INPUTS (in your case, RADIO services, listed as HTTP URIs like my initial M3U example) and it publish these RADIO services. I suspect in your case as a HTTP MP3 streaming resources. But if two (or more) clients request the SAME service, then the transcoder only request the source one time, transcode it, and sends it to the different clients. That's all, simple and clear.

Take note that the architecture it's identical putting the transcoding functionality _inside_ minisatip that in a external process. However, what you want (from my point of view) is that other people resolve your problem providing one all-in-one binary that provides the functionality. And this is not  the approach of open and collaborative projects, and neither of the common and well-known ingest-transcoder-streaming platforms. I've a lot of years of experience in such type of environments. And what you need is already implemented for years. So please, spend a litte time for finding for some transcoder. You can configure what you need in less than 1 hour.

I hope this helps you. And note than I'm expressing my opinion. Perhaps the author of minisatip (@catalinii) have a different point of view.
Regards.

**Comment by UKenGB** [comment]
Well since I am obviously so lazy and incapable of doing any research myself into this, please enlighten me as to where I can find such transcoders that have been doing for years what I require.

Needless to say, I find your comments about my question objectionable and it is laughable that you state this can all be easily accomplished in an hour, while it has to be said, actually supplying no information as to how one might actually achieve your claims.

I understand (although a little disappointed) if the author of minisatip does not wish to include such functionality, but that is not for you to say, nor to make such disparaging and wildly inaccurate criticisms of anyone who dares to suggest such a feature.

Of course, if you can suggest a transcoder that can do what you say and that can be set up inside an hour, then I’m all ears…


Ken  G i l l e t t

_/_/_/_/_/_/_/_/

**Comment by lars18th** [comment]
> Well since I am obviously so lazy and incapable of doing any research myself into this, please enlighten me as to where I can find such transcoders that have been doing for years what I require.

> Of course, if you can suggest a transcoder that can do what you say and that can be set up inside an hour, then I’m all ears…

As I commented before, I feel you don't want to do any research.

However, as my idea is to help, here's my recomendation:
- minisatip: as the sat tuner server publishing on-demand services over HTTP.
- astra-sm: as the transcoder server. It ask for the service over HTTP and uses the PIPE module to transcode. Use the regular (on-demand) HTTP output.
- ffmepg: as the real transcoder. Call it using pipes from astra-sm.
 
With only these three tools you can setup a robust server in less than 20 minutes.

However, if you want a more professional solution, then try with some DAB tools. For example: https://github.com/piratfm/eti-tools. You can use for example tools from OpenDigitalRadio to provide a HTTP-on-demand MP3 radio server. The ingest point will be then the HTTP radio services that you can define in a M3U file (test it first with VLC), instead of ETI inputs.

So, please stop to ask to integrate transcoding inside minisatip. IMHO, this not have sense... as anyone with small background can explain.
Regards.

**Comment by UKenGB** [comment]
Thanks for the recommendation of astra-sm, I am currently looking at something similar and will now also look at astra-sm. I also looked into eti-tools, but not exactly what I need.

As for the rest:-

First of all, incorporating transcoding into minisatip is not a frivolous request and indeed I am not the first - hence the reason for this thread. As for requesting features to suit oneself, I rather think you have the record there.

Secondly, you know NOTHING about what research I may or may not have conducted. Maybe your life revolves around this stuff and you already know it all. I don’t. Until a few days ago I had never considered streaming of any sort and so it takes a while to gain knowledge and understanding and that can always be helped by assistance from others. Something I am always happy to do when I am in the position of greater knowledge. In which case I try to assist without rude and sneeringly dismissive remarks aimed at the questioner. You and people like you ruin the forum experience for others. Well done.

As for me, I’m done with this. I thought minisatip a great product, with or without transcoding. My only problem really is you. So don’t bother with any more of your so called ‘help’ and baseless criticism. I’ll figure it out for myself.


Ken  G i l l e t t

_/_/_/_/_/_/_/_/

**Comment by UKenGB** [comment]
So others who "don't want to do any research” can benefit?

No chance of that sunshine. You blew it.


Ken  G i l l e t t

_/_/_/_/_/_/_/_/

**Comment by Jalle19** [comment]
Let's be honest here - transcoding is no easy feat and it's much more suitable to be implemented as a separate service that uses minisatip's RTSP or HTTP streams as input.

tvheadend can handle it for example, and there are probably other more modern solutions as well if you want HLS output or something similar.
