### ISSUE TITLE
improvement: ssdp

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#302]
can we change the msearch port 1900 to SO_REUSEADDR?

**Comment by catalinii** [comment]
Hi,

SO_REUSEADDR is set for the socket listening on 1900 (see socketworks.c : 138).
Is this not working properly ?

thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

I put this here because I belive is related with the problem found by @9000h .

The current code of minisatip for opening the SSDP socket, is using the wrong address for *listening*.

In the function 'udp_bin()' in "socketworks.c" the current algoritm is this:

- Create the socket
- Join the multicast group
- Set the shared listening option (SO_REUSEADDR)
- Bind the socket (start listening)

And the listening address is set to '239.255.255.250:1900'.
However, this doesn't work in a system where the multicast address isn't already running.

So, the right way is this:

- Create the socket
- Set the shared listening option (SO_REUSEADDR)
- Bind the socket (start listening)
- Join the multicast group

And the trick is set the *listening* address to ANY (0.0.0.0). This is right because you send SSDP messages TO the multicast address, and the system receives all messages FROM the multicast group when you're in the group.

The result with current implementation is that on several platforms minisatip fails to open the SSDP socket.

Here my workaround for "socketworks.c":

```
	if (!fill_sockaddr(&serv, addr, port))
		return -1;
+	serv.sin_addr.s_addr = htonl(INADDR_ANY);
	sock = socket(AF_INET, SOCK_DGRAM, 0);
	if (sock < 0)
```

And then change the order of the three 'if blocks':

```
if (setsockopt(sock, SOL_SOCKET, SO_REUSEADDR,...
...
if (bind(sock, (struct sockaddr *)...
...
if (addr && atoi(addr) >= 239)...
...
```

Please, try it and commit the changes!
I hope you agree. :)
Regards!

**Comment by catalinii** [comment]
Hi,

what is the actual issue that you are seeing and how to reproduce it ?

For me listening on 239.255.255.250 just works, without additional setup...

**Comment by lars18th** [comment]
Hi @catalinii ,

```
./minisatip.exe -f -s 192.168.1.35:554 -l
[01/06 12:17:00.764]: minisatip version 0.5.51, compiled with s2api version: 0000
[01/06 12:17:00.764]: Built without dvbcsa
[01/06 12:17:00.765]: Built without CI
[01/06 12:17:00.765]: Built without dvbapi
[01/06 12:17:00.765]: Built without AES (OpenSSL)
[01/06 12:17:00.765]: Built without tables processing
[01/06 12:17:00.765]: Built with satip client
[01/06 12:17:00.765]: Built without linux dvb client
[01/06 12:17:00.766]: Built without backtrace
[01/06 12:17:00.766]: Built without netceiver
[01/06 12:17:00.767]: New UDP socket 3 bound to 0.0.0.0:1900
[01/06 12:17:00.767]: setting multicast for 239.255.255.250
[01/06 12:17:00.768]: udp_bind: failed: bind() on host 239.255.255.250 port 1900: error Cannot assign requested address
[01/06 12:17:00.769]: SSDP: Could not bind on 239.255.255.250 udp port 1900
```

This behaviour only appears (in my tests) in Cygwin, but i feel it can appear in other platforms... the error is: "you can't bind to the multicast address!". You need to bind to some local address, and after the bind then join the multicast group.

You agree?

**Comment by lars18th** [comment]
Hi @catalinii ,

You agree my proposal?

**Comment by catalinii** [comment]
Hi 

Is the latest commit fixes the 1900 port listening issues (as it tries to listen on all ips if listening 239.255.255.250)?

Thanks
