### ISSUE TITLE
Patch: Support for standard LNBs used for Sky TV New Zealand

### ISSUE THREAD

**Issue by fe31nz** [catalinii/minisatip#316]
Here in New Zealand, we have only one major pay TV operator, Sky TV (nothing to do with the British Sky as far as I know).  They supply the majority of installed dishes in New Zealand and most of the other installers tend to follow what Sky are doing with their own installations.  As we have only one satellite providing channels (Optus D1), Sky dishes use a "standard" LNB (one that has only one local oscillator).  But over the years they have used a variety of hardware with different local oscillator frequencies (LOFs).  Current installs (and mine) use a LOF of 10750 MHz, but there are at least another three LOFs used in New Zealand.  Also, on older dishes there can be a problem where the local oscillator has drifted and it is necessary to adjust the LOF value a little to get a good signal.

Minisatip does not have support for setting the LOF, and hence did not work on my dish as it was defaulting to a LOF of 10600 MHz (LOF2 define in the code).  So I have done a patch that adds a new command line option (-L --lof <lof_freq>) that allows the LOF to be set to any value.  Using that option also causes minisatip to be configured for a "standard" LNB.  See the attached diff.txt for a git diff of the patch.

I have this patch working on my Mythbuntu 14.04 system with my TBS 5922 DVB-S2 card, and I can now use minisatip with all the free-to-air and encrypted channels I have tried on that card, both DVB-S and DVB-S2.  Decryption is in software via DVBAPI and Oscam.

There is still a problem using my TeVii S470 DVB-S2 card - it does not seem to tune properly yet.  That is likely to be something to do with how that card works, as it is an older card that does not automatically swap between DVB-S and DVB-S2, and does not show DVB-S2 channels when I scan it using dvbtune and scan-s2.  I am still working on that and will post another issue if I find out what the problem is.

[diff.txt](https://github.com/catalinii/minisatip/files/358839/diff.txt)

**Comment by catalinii** [comment]
Hi,

Thanks for the report.

I was looking a bit and I think this is more like a general problem as the current code uses the LOF* values hard coded. 

The best way to fix this is to make all the values configurable via command line, where you can configure the low value, the high value and the switch frequency..

Thanks.

**Comment by catalinii** [comment]
I will fix this as soon as possibile...

**Comment by catalinii** [comment]
Hi,

can you try:

-L *:10750:10750:10750 

Thanks

**Comment by fe31nz** [comment]
Using -L *:10750:10750:10750 is not working as the -L option is not being parsed correctly.  First, the getops_long call in minisatip.c needs "L:" added to the options string.  Second, the LOG macro does not appear to work when used in set_lnb_adapters - I think the options parsing must be being done before the LOG macro prereqisites have been set up.  When I added a printf to display the same message above the LOG call in set_lnb_adapters, I got the "LNB parameters not correctly specified" error message.  Looking at the code directly above the LOG call, I can see that sep3 will always be NULL and hence that error will always occur.  I have not worked out how you are doing the parsing yet, but as it is now midnight here in New Zealand,  I am stopping testing for tonight.  I will take another look tomorrow to see if I can fix it.

**Comment by catalinii** [comment]
Hi,
Try now but with *:10750-10750-10750
Thanks

**Comment by fe31nz** [comment]
That has fixed it!  Thank you!

**Comment by Quantomax** [comment]
Hi catalinii:
With "-L 0:9749-10599-11700,1:9749-10599-11700" to compensate LNC frequency-shift I'll get this

Setting diseqc adapter 0 lnb_low 9749000 lnb_high 10599000 lnb_switch 10599000
Setting diseqc adapter 1 lnb_low 9749000 lnb_high 10599000 lnb_switch 10599000

commandline output and some non working channels. Seems switch freq parsing still broken.

**Comment by Quantomax** [comment]
lnb_switch = map_intd(sep2 + 1, NULL, -1) * 1000; 

sep2 should be sep3, I think. :)

**Comment by catalinii** [comment]
Hi,

thanks for the patch,

please let me know how it works now.

**Comment by dadittoz** [comment]
Hello,

Do I understand correctly that currently LNB settings work per adapter only? Is it possible to configure it per LNB through DiSEqC rather than for the whole adapter? I have one 36E LNB that uses LOF of 10750, but all other heads are Universal LNB. They are all connected through DiSEqC. Setting LOF for the whole adapter renders all other connected LNBs unusable, except for 36E.

**Comment by catalinii** [comment]
Hi,

If it's circular polarity (for 10750) and universal the other ones (h,v) it should work out of the box

But yeah you can specify LOF per adapter.

Thanks

**Comment by dadittoz** [comment]
Unfortunately, looks like my current installation uses Universal LNB, that was physically adjusted for circular reception. So it sends H/V instead of L/R. 

I was just trying to move from dreambox to kodi + tvheadend + minisatip setup. Took some time to understand what's going wrong and why I am missing some channels. My satellite install was made by local professional, so I wasn't even aware of this problem until I decided to move to a new setup.

I guess there are two options possible to make it work:
1) Add an override option to convert incoming polarity L -> H, R -> V per LNB. Pros: probably less coding, good for tvheadend network scan (no need to manually replace polarity). Cons: looks like a hack.
2) Add LOF settings per LNB. Pros: universal, logical. Cons: more coding, tvheadend network scan won't work great.

Looks like adjusting universal LNB to receive circular signal is rather common thing that people do in Russia. There's a topic with more than 100 pages at one Russian forum about it. It would be great if minisatip could somehow support this.

**Comment by catalinii** [comment]
Hi,

1) issue 1 sounds a bit like a hack...u can put it as a RFE...if there are many users wanting it I will implement it.

2) LOF settings are per adapter or for all adapters (*).
Thanks
