### ISSUE TITLE
some channels cannot decrypt anymore

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#582]
since the last commit https://github.com/catalinii/minisatip/commit/2a4d557cd25d1ca841f3d1540f18c447768e88f1 some channels cannot decrypt anymore 
as an example "kabel eins HD" caid 1860
```
kabel eins HD;ProSiebenSat.1:11464:HC23M5O35P0S1:S19.2E:22000:767=27:0;771=deu@106:34:1830,1843,9C4,98C,1860,186A,98D,186D,500,6CB,1842,4B64:61302:1:1017:0
```
oscam log
```
2019/04/17 21:13:00 714590EA c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 09C4 ECM_PID: 1BEE PROVID: 000000 
2019/04/17 21:13:00 714590EA c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 098C ECM_PID: 1AEE PROVID: 000000 
2019/04/17 21:13:00 714590EA c   (dvbapi) Demuxer 0 ecmpid 2 CAID: 0648 ECM_PID: 1FED PROVID: 000000 
2019/04/17 21:13:00 714590EA c   (dvbapi) Demuxer 0 ecmpid 3 CAID: 0650 ECM_PID: 1FEF PROVID: 000000 
2019/04/17 21:13:00 714590EA c   (dvbapi) Demuxer 0 ecmpid 4 CAID: 0500 ECM_PID: 1FEE PROVID: 051900 
2019/04/17 21:13:00 714590EA c   (dvbapi) Demuxer 0 ecmpid 5 CAID: 06E2 ECM_PID: 1EEF PROVID: 000000 
2019/04/17 21:13:00 714590EA c   (dvbapi) Demuxer 0 ecmpid 6 CAID: 098D ECM_PID: 18EE PROVID: 000000 
2019/04/17 21:13:00 714590EA c   (dvbapi) Demuxer 0 found 7 ECMpids and 3 STREAMpids in caPMT
2019/04/17 21:13:00 714590EA c   (dvbapi) Demuxer 0 trying to descramble PID 2 CAID 0648 PROVID 000000 ECMPID 1FED ANY CHID PMTPID 0082 VPID 02FF
2019/04/17 21:13:00 714590EA c   (dvbapi) Demuxer 0 found 7 ECMpids and 3 STREAMpids in PMT
2019/04/17 21:13:00 714590EA c      (ecm) satip (0648@000000/0015/EF8A/44:E38381ED63F5972196588EFF82907276): not found (1 ms) by ORF - kabel eins HD Austria
```
patch reverted
```
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 0 CAID: 1830 ECM_PID: 1CEE PROVID: 000000 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 1 CAID: 1843 ECM_PID: 19EE PROVID: 000000 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 2 CAID: 09C4 ECM_PID: 1BEE PROVID: 000000 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 3 CAID: 098C ECM_PID: 1AEE PROVID: 000000 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 4 CAID: 1860 ECM_PID: 1EEE PROVID: 000000 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 5 CAID: 186A ECM_PID: 1DEE PROVID: 000000 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 6 CAID: 098D ECM_PID: 18EE PROVID: 000000 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 7 CAID: 186D ECM_PID: 1DEF PROVID: 000000 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 8 CAID: 0500 ECM_PID: 1FEE PROVID: 051900 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 9 CAID: 06CB ECM_PID: 1BEF PROVID: 000000 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 10 CAID: 1842 ECM_PID: 1CEF PROVID: 000000 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 ecmpid 11 CAID: 4B64 ECM_PID: 1CEF PROVID: 000000 
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 found 12 ECMpids and 4 STREAMpids in caPMT
2019/04/17 21:21:14 714590EA c   (dvbapi) Demuxer 1 trying to descramble PID 4 CAID 1860 PROVID 000000 ECMPID 1EEE ANY CHID PMTPID 0062 VPID 02FF
2019/04/17 21:21:14 714590EA c      (ecm) satip (1860@000000/0000/EF76/8F:1E3C2484F7E848F94E1F4C24628C4272): found (323 ms) by HD03 - kabel eins HD
```

**Comment by catalinii** [comment]
Can you send me the log with and without the patch?

**Comment by localhosthack0r** [comment]
Hi,
same here. As a quick workaround I removed the check 
 	if(pmt->id != pmt->master_pmt) 
from start_pmt() in pmt.c

I think the reason is that HDplus and Austriasat share some PIDs (Video/Audio/PCR/...), but have different PMT PIDs on some channels, i.e.:
https://www.satindex.de/channel/5275/
https://www.satindex.de/channel/22811/

Will try to provide logs, as well, the next days,....

**Comment by 9000h** [comment]
latest git
bad
rtsp://192.168.178.129/?src=1&freq=11464&pol=h&ro=35&plts=1&mtype=8psk&msys=dvbs2&sr=22000&fec=23&pids=0,18,34,771,767
http://paste.ubuntu.com/p/ntQJx4FVB5/

good (added pmt pid 98)
rtsp://192.168.178.129/?src=1&freq=11464&sr=22000&fec=23&ro=35&plts=1&pol=h&msys=dvbs2&pids=0,34,767,771,98
http://paste.ubuntu.com/p/N2pnxMg5T6/

could be also that the pmt auto detection fails somehow

the latest commit did break it for VDR but with VLC it did not work before the latest commit (only by adding the right pmt pid)

**Comment by catalinii** [comment]
Do you have a list of channels that do not work? Ideally I would like to keep sending just 1 pmt to the DVBAPI instead of all.

**Comment by 9000h** [comment]
as @localhosthack0r wrote I saw it with HDplus and Austriasat, they share caids but can happen probably on other packages to.

**Comment by localhosthack0r** [comment]
Hi, 
sorry for letting you waiting so long, here the logs (-l pmt,dvbapi,ca ):

Here with outcommented PMT check, as mentioned above, the encryption works fine:
https://pastebin.com/kT3tpK6m

Here unmodified sources, no encryption:
https://pastebin.com/nai9iwr1

**Comment by catalinii** [comment]
Reverted the behavior in the last diff

**Comment by 9000h** [comment]
ok VDR is happy now, but the pmt auto detection on some channels is still picking up the wrong pmt
test m3u for VLC, first one is working by adding the right pmt to the pids. The second one did pick up the wrong pmt.
```
#EXTM3U
#
#EXTINF:-1,kabel_eins_HD;ProSiebenSat.1 pmt
rtsp://192.168.178.129/?src=1&freq=11464&sr=22000&fec=23&ro=35&plts=1&mtype=8psk&pol=h&msys=dvbs2&pids=0,34,767,771,98
#EXTINF:-1,kabel_eins_HD;ProSiebenSat.1 
rtsp://192.168.178.129/?src=1&freq=11464&sr=22000&fec=23&pol=h&ro=35&plts=1&mtype=8psk&msys=dvbs2&pids=0,34,767,771
```

**Comment by localhosthack0r** [comment]
> Reverted the behavior in the last diff

Thank you @catalinii ! That makes it working for me again, because now in the case of these HDplus channels both PMTs are requested from dvbapi:
At one I have no matching readers, at the other one I get a found. In oscam log, this looks like:
`2019/04/28 17:41:59 24BB70E8 c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 09C4 ECM_PID: 1BEE PROVID: 000000 
2019/04/28 17:41:59 24BB70E8 c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 098C ECM_PID: 1AEE PROVID: 000000 
2019/04/28 17:41:59 24BB70E8 c   (dvbapi) Demuxer 0 ecmpid 2 CAID: 0648 ECM_PID: 1FED PROVID: 000000 
2019/04/28 17:41:59 24BB70E8 c   (dvbapi) Demuxer 0 ecmpid 3 CAID: 0650 ECM_PID: 1FEF PROVID: 000000 
2019/04/28 17:41:59 24BB70E8 c   (dvbapi) Demuxer 0 ecmpid 4 CAID: 0500 ECM_PID: 1FEE PROVID: 051900 
2019/04/28 17:41:59 24BB70E8 c   (dvbapi) Demuxer 0 ecmpid 5 CAID: 06E2 ECM_PID: 1EEF PROVID: 000000 
2019/04/28 17:41:59 24BB70E8 c   (dvbapi) Demuxer 0 ecmpid 6 CAID: 098D ECM_PID: 18EE PROVID: 000000 
2019/04/28 17:41:59 24BB70E8 c   (dvbapi) Demuxer 0 found 7 ECMpids and 3 STREAMpids in caPMT
2019/04/28 17:41:59 24BB70E8 c   (dvbapi) Demuxer 0 no suitable readers found that can be used for decoding!
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 0 found 7 ECMpids and 3 STREAMpids in PMT
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 0 CAID: 1830 ECM_PID: 1CEE PROVID: 000000 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 1 CAID: 1843 ECM_PID: 19EE PROVID: 000000 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 2 CAID: 09C4 ECM_PID: 1BEE PROVID: 000000 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 3 CAID: 098C ECM_PID: 1AEE PROVID: 000000 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 4 CAID: 1860 ECM_PID: 1EEE PROVID: 000000 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 5 CAID: 186A ECM_PID: 1DEE PROVID: 000000 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 6 CAID: 098D ECM_PID: 18EE PROVID: 000000 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 7 CAID: 186D ECM_PID: 1DEF PROVID: 000000 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 8 CAID: 0500 ECM_PID: 1FEE PROVID: 051900 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 9 CAID: 06CB ECM_PID: 1BEF PROVID: 000000 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 10 CAID: 1842 ECM_PID: 1CEF PROVID: 000000 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 ecmpid 11 CAID: 4B64 ECM_PID: 1CEF PROVID: 000000 
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 found 12 ECMpids and 4 STREAMpids in caPMT
2019/04/28 17:42:00 24BB70E8 c   (dvbapi) Demuxer 1 trying to descramble PID 0 CAID 1830 PROVID 000000 ECMPID 1CEE ANY CHID PMTPID 0062 VPID 02FF
2019/04/28 17:42:00 24BB70E8 c      (ecm) vdr (1830@000000/0000/EF76/92:20E3DB584BC592149EBD6D4AA2B600A1): cache3 (0 ms) by x - kabel eins HD
2019/04/28 17:42:01 24BB70E8 c   (dvbapi) Demuxer 0 no enabled matching ecmpids -> decoding is waiting for matching readers!
2019/04/28 17:42:06 24BB70E8 c   (dvbapi) Demuxer 0 no enabled matching ecmpids -> decoding is waiting for matching readers!
2019/04/28 17:42:08 24BB70E8 c      (ecm) vdr (1830@000000/0000/EF76/92:8B1AC2C50C376BE9E3E5F35E5FC3C8F6): cache3 (330 ms) by x (L/1/8/8) - kabel eins HD (cwc OK(CE))
2019/04/28 17:42:11 24BB70E8 c   (dvbapi) Demuxer 0 no enabled matching ecmpids -> decoding is waiting for matching readers!
2019/04/28 17:42:16 24BB70E8 c   (dvbapi) Demuxer 0 no enabled matching ecmpids -> decoding is waiting for matching readers!
2019/04/28 17:42:21 24BB70E8 c   (dvbapi) Demuxer 0 no enabled matching ecmpids -> decoding is waiting for matching readers!
2019/04/28 17:42:23 24BB70E8 c      (ecm) vdr (1830@000000/0000/EF76/92:59EA79E705E9B223B810CEE8EED092FC): cache3 (375 ms) by x - kabel eins HD
`
Would it be possible to request just one PMT, if the x_pmt parameter is given? If no x_pmt is given, of course, it makes sense, to try all PMTs, IMHO.

@9000h 
From which tool do you generate your VLC m3u? I use octpus cast tool, from digital devices 
and there I have the x_pmt parameter.
https://www.digital-devices.eu/shop/de/tools

Example:
rtsp://@mmslave/?src=1&freq=11464&pol=h&msys=dvbs2&sr=22000&pids=0,98,767,34,771,767&x_pmt=98

**Comment by 9000h** [comment]
my m3u is hand made :-)

**Comment by catalinii** [comment]
Even if it is hand made it should still send 2 or more pmts

**Comment by 9000h** [comment]
will close here as the auto pmt is a different issue
