### ISSUE TITLE
diseqc options

### ISSUE THREAD

**Issue by engalaaodeh** [catalinii/minisatip#778]
Hi,

First I need to thank for your kindly support , I have one question please about diseqc option 
we have two server using SATIP

main server : 
A - SATIP 192.168.1.10 
4 tuner and diseqc 1.0
port A : Nilesat
port B : Arabsat
port C : Hotbird
port D : Astra 19

second server 

B- SATIP 192.168.1.11
4 tuners  and diseqc 1.0
port A : Eutelsat
port B : Nilesat
port C : Astra 28
port D : Turksat

my command to connect two server on main server 

./minisatip -O  -i 32 -H 1:5 -b 18048:5775360 -B 18000  -s 192.168.1.11:554 -U 0-7:0-7:0-7:0-7

and I am using enigma2 openatv and connect to main server 192.168.1.10 and how we can choose sat Astra 28 from tuner number 6 with diseqc port C ?

can we set a default diseqc for tuner as a static and ignore any diseq parameter from enigma2 ?

**Comment by catalinii** [comment]
In this situation you have 2 tuners not 1. While you may want to make them look like 1 tuner in enigma this has downsides as well such as using just one tuner at one time. I.e. you cannot watch Astra 19 and Astra 28 at the same time.

The diseqc setup is pretty standard everywhere. src=X indicate diseqc position x.

The issue is enigma satip client does not use fe= to select the correct tuner

**Comment by catalinii** [comment]
The issue has been fixed meanwhile on minisatip using -A or in enigma2 satipclient. More details: https://github.com/catalinii/minisatip/issues/896
