### ISSUE TITLE
Use as SAT>IP Client?

### ISSUE THREAD

**Issue by joeduck** [catalinii/minisatip#8]
Hi,

thanks for this cool software. i have read in the readme that it also can emulate DVB-S Cards on a system and connect to the Server part. Is it also possible to use the client part to connect to a normal SAT>IP Server like the Inverto iLNB?

Thanks in Advance

**Comment by catalinii** [comment]
Hi,

what I meant was that the application can report more tuners than physically available (and it works as long as you tune to the same transponder), but it cannot act as a satip client. Theoretically it should not be needed to have the app act as satip client because the protocol was designed for multiple satip servers to co-exist in the same network and the client to connect to the satip  server that has required streams. 

If your need is to use multiple servers from multiple locations (or over internet) probably you can go with openvpn, tap interfaces and use bridges in case you have more than 2 servers (I am not sure if openvpn by itself can route multicasts when a star topology is used, this is why it might be needed to add bridges on top of openvpn)

Thank you
