### ISSUE TITLE
Share tuner (adapter) with close frequencies

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#802]
Hi @catalinii ,

After the PR #801 I see this use case: When one client requests a frequency that is not rounded, rounding to the next digit; and after another client requests the **same** transponder but using the frequency rounded to lower. In this case, the second request fails.

So, it will have sense to use an interval (around [+1,-1] Hz) when searching for an adapter using the same parameters?
What you think?

**Comment by Wanninger** [comment]
I see the same problem with simply assigning clients to tuners. Minisatip always tries to collect clients that want to use the same transponder on a single tuner. Unfortunately, this works only if all parameters evaluated for it are 100% identical. A simple example where it does not work is e.g. when using two different client types.

VDR requests ZDF HD on 11362 MHz-H and
Enigma2 requests ZDF HD on 11363 MHz-H.

Since both are not 100% identical, minisatip assigns an extra tuner to each of VDR and Enigma2.

Maybe minisatip could be told to extend the tolerance on the frequency to +/-1MHz
from the nominal value. Then - for example - 11362MHz and 11363MHz would be able to use the same tuner. In the end, the difference is only wastepaper, because both want the same transponder and have only a difference in the notation in the channel list.

**Comment by lars18th** [comment]
Hi @Wanninger ,

> Maybe minisatip could be told to extend the tolerance on the frequency to +/-1MHz

Yes, that's the idea. However, we need that @catalinii will explain where to put the code to address the tolarence. Any idea?

**Comment by Wanninger** [comment]
Unfortunately not. I am not a programmer and have at best rudimentary (actually none) knowledge of coding.

I raised this issue two years ago when I noticed the problem with VDR and Enigma2, but didn't pursue it at the time.

There may even be more than just the transponder frequency that can lead to the effect.So I noticed during my tests that possibly also the client type and the transport type, could have an influence on it. However, I would have to investigate this again in more detail.

I am currently in contact with Catalin for many functional tests and additional functions for minisatip server. I will just ask him about it.

**Comment by lars18th** [comment]
Hi @Wanninger ,

> I am currently in contact with Catalin for many functional tests and additional functions for minisatip server. I will just ask him about it.

That's perfect!

**Comment by 9000h** [comment]
hmm, probably freq/1000 and it's may also a negative offset

**Comment by catalinii** [comment]
It should be probably 
abs(tp->freq - ad->tp.freq) < 1000 or something like that to set the tolerance.

**Comment by 9000h** [comment]
any comments about the PR?

**Comment by lars18th** [comment]
> any comments about the PR?

I need to check it.

**Comment by lars18th** [comment]
> any comments about the PR?

It seems to work as expected. Now running with this patch.
Thank you!

**Comment by 9000h** [comment]
great so close please
