### ISSUE TITLE
Question: Monitoring with JSON

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#884]
Hi,

This question for anyone that is monitoring the minisatip server with some tool (Grafana or similar). We have a JSON HTTP API embbeded in the minisatip: `http://minisatip:8080/state.json`. So we only need to use it.

Any ideas or experience with this?
Regards.

**Comment by Jalle19** [comment]
I haven't used it, but I've been thinking of whipping up a better web interface that's more suitable for mobile phones/tablets

**Comment by Jalle19** [comment]
I started using this along with bandwidth.json, don't have anything to show just yet though.

**Comment by lars18th** [comment]
Oh, then try to write what improvement we could do.

**Comment by Jalle19** [comment]
My initial thought is to change the JSON structure to not have static length arrays. I'm not yet sure what I need though so I don't have any concrete suggestions.

**Comment by Jalle19** [comment]
I found two additions that I think could be helpful:

`ad_pids: [1, 2, 3, 4]` instead of a comma-separated string. This can by extension be used to determine whether an adapter is active or not (length of the array would be zero).

It's probably best to add a separate field instead of changing the structure of the old one.

**Comment by Jalle19** [comment]
Closing due to nothing actionable.
