### ISSUE TITLE
two servers with diseqc 

### ISSUE THREAD

**Issue by odehalaa** [catalinii/minisatip#896]
Hi,

Kindly if I have two Minisatip servers and each one have diseqc 1.0   4 sat A,B,C,D and connect two servers on one server
and if we are using enigma2 how we can detect server 1 port B or server 2 port B

I suggest to add virtual diseqc option if possible please?

Best Regards

**Comment by catalinii** [comment]
The main issue is that enigma satip client cannot differentiate between adapters. The best fix would be to open an issue (if it does not exist yet) to handle this use case.

**Comment by odehalaa** [comment]
I used enigma satip client but no problem , if we connect two satip servers and each one have diseqc  4 ports and different sats how we can choose the sat if the first server use different from the second one ?

I suggest to add virtual diseqc number for sat and optional like if we need diseqc port 14 set to diseqc port 4 from the first one
and if diseqc port 15 set to server b and diseq port 3 if possible please ?

**Comment by lars18th** [comment]
Hi @odehalaa ,

What you need is to configure the minisaitp on each STB boxes with the parameter `-U --sources sources_for_adapters`. In the first server you can enable positions 1-4, and in the second one the position 5-8. Then in the SAT>IP client you can configure server 1 to pos 1-4, and server 2 for pos 5-8. With this configuration you can reach all eight positions without problems.

I hope this helps you.
Regards.

**Comment by catalinii** [comment]
@lars18th, can you please provide a sample command line for this case?

Maybe we can document it in the help message

**Comment by lars18th** [comment]
Hi @catalinii ,

It's already documented: https://github.com/catalinii/minisatip/blame/master/README.md#L196-L202

Example with two boxes, each one with 1 tuner connected to 4 (different) sat positions:
- Server 1: `minisatip -U 0:0:0:0:~:~:~:~` (or `-U *:*:*:*:~:~:~:~` if the server has more than one adapter and share same sats).
- Server 2: `minisatip -U ~:~:~:~:0:0:0:0` (or `-U *:*:*:*:~:~:~:~` if the server has more than one adapter and share same sats).

Then from the point of view of any client: `src=1..4` will be only available on server 1, and `src=5..8` on server 2. If your client can't distinguish, then you can interpose a new minisatip instance using the `satipc` module. And here you only need to configured it as:
- Client server: `minisatip -U 0:0:0:0:1:1:1:1 -s server1ip -s server2ip`

You check/view the configuration using the command `-f -v adapter` when launching minisatip.

Regards.

Note: The `~` could be used in the list to represent "empty" adapters. This isn't documented, so we can add it.

**Comment by lars18th** [comment]
Hi @catalinii ,

> Maybe we can document it in the help message

Please, merge the PR #920 .

**Comment by catalinii** [comment]
@lars18th I think there is still an issue here if we have for example 2 cables connected to 2 adapters:
cable 1) Diseqc 2 positions (astra 19, hotbird 13)
cable 2) Diseqc 2 positions (astra 23, thor 1w)

As enigma satip cannot differentiate between adapter 1 and 2 (as it does not send fe=), my understanding is that -U will not solve this issue.

For minisatip the only option is to have something like free-inputs (which is enabled just for axe).

I will probably try to fix the enigma2 satipclient if I have time to send fe.

**Comment by lars18th** [comment]
Hi @catalinii ,

First of all, please remember what the Specifications of the SAT>IP protocol indicates: "The `fe=` parameter will not be used by clients" (Section 3.5.11).

In the use case that you describe, the solution is quite simple: assuming adapter 0 is connected to cable 1 (astra 19, hotbird 13) and adapter 1 is connected to cable 2 (astra 23, thor 1w), then you only need to configure minisatip with `-U 0:0:1:1`. Then _all_ clients that will connect to minisatip will see that src=1 is Astra 19, src=2 is HotBird 13, src=3 is Astra 23, and src=4 is Thor 1W. All transparently. The clients don't need to use `fe=` (and they wont never use it). And the enigma2 satipclient will work as expected configuring the server with DiseqC 4x1 (that's with sources 1-4). Where is then the problem? I've created time ago this `-U` option just for this use case!

**Comment by catalinii** [comment]
Hey @lars18th,

I think there is a piece missing that maps the original source (for example 3 in this case - Astra 23) to the src = 1 on the original adapter.
This is an example for me:
The client requests src=3:
[26/01 17:59:27.594 main]: MSG client >> process :
PLAY rtsp://192.168.100.2:554/stream=1?src=3&freq=11938&pol=h&msys=dvbs&sr=28000&fec=78
&ro=0.35&mtype=qpsk&plts=off RTSP/1.0

Then the adapter 1 is correctly chosen, but the source is kept to being 3 (instead of 1):
[26/01 17:59:27.782 main]: satipc_http_request (adapter 1): sending to sock 11
[26/01 17:59:27.782 main]: MSG process >> server :
PLAY rtsp://192.168.5.8:5544/?src=3&freq=11938&msys=dvbs&mtype=qpsk&pol=h&sr=28000&fec=78&ro=0.35&plts=off&pids=0 RTSP/1.0

Going over the source code, there is no src= remapping feature (or maybe I missed it).

For enigma specific use case, I have added support for fe: https://github.com/oe-alliance/satip-client/pull/19 so once this is merged you can select whichever adapter is needed.

For me this is still an issue as my enigma2 receiver has just 2 adapters so I still need -U option.

**Comment by lars18th** [comment]
Hi @catalinii ,

> Going over the source code, there is no src= remapping feature (or maybe I missed it).

Oh, yes! You're right. In that case the second SAT>IP server will receive "src=5" to "src=8". I missed this!

Perhaps, we can add a simple "src-remapping" in the `-s --satip-servers` parameter to solve this problem. For example with this syntax: `--satip-servers [~][*][%5-1,6-2,7-3,8-4][DELSYS:][FE_ID@][source_ip/]host[:port]`. So with `%` we describe the mapping list: first the guest source and after the `-` the target source.

What you think?

Note: Regarding the oe-alliance repository. Please, could you provide a PR to update the minisatip package? I feel with the last changes of version numbers, the package is not updated with new releases.

Regards.

**Comment by catalinii** [comment]
I think more straightforward may be to re-use -U and create both the mapping and the current functionality.

I feel --free-inputs is more general, as it allows mapping multiple adapters and diseqc positions to one virtual src= entry, but with the enigma2 issue fixed, maybe there is no point to implement the complex case.

About minisatip version, it should follow master:
# opkg update && opkg list | grep minisatip
minisatip - 1.0d+git0+c5b6945c1a-r0 - SAT>IP server

c5b6945c1a -> is basically the latest PR.

**Comment by catalinii** [comment]
@odehalaa @lars18th 
I have extended -A (-virtual-diseqc) to cover the use case of -U as well.
I am using with 2 cables both with DISEQC (19E, 13E on adapter 0, 23E,1W on adapter 1) :
-A 0:0:0,1:0:1,2:1:0,3:1:1
- virtual position 0, adapter 0, first diseqc position
- .....
- virtual position 3, adapter 1, second diseqc position.

**Comment by lars18th** [comment]
Hi @catalinii ,

Thank you for the improvement. However, a huge change (I'm using the `-U` parameter), so a I need to change all my (complex) configuration.

And I've some questions because I don't understand the new command:

- First, I'm sure at 99% that the first parameter is the SRC requested by the SAT>IP client, and the third is the DiseqC value to what it corresponds in the adapter, right? In this case, one small suggestion: add support to pass as the third parameter the value `*`. This have sense if the adapter is a satipc module, and you want to pass the original SRC value. Example: `-A 0:0:*`. In this case you could pass up to the 32 values.
- Sencond question is the new limit of the SRC value. Someone has requested time ago to support up to 64 positions. Why you've reduced it now to 32? It isn't safe to change to 64?
- Third question is about the *second* value. It represents perhaps the _adapter_ or _tuner_? If yes, then why you limit it to only four adapters? Using the satipc module we've a lot more than 4 servers. If not, then please explain what it represents.

I hope you can answer soon.
Thank you.

**Comment by catalinii** [comment]
1) In the current situation how do u see * working ? Pass all src from 1-32 or 64 ? -A 0:0:* would translate to 0:0:0, 1:0:1 , ... 31:0:31 ?

2) Just the message is wrong. Internally it supports up to 64 sources

3) Same as before, is the adapter but is not limited to 4 adapters, but all adapters can use the feature.

**Comment by lars18th** [comment]
Hi @catalinii ,

Thank you for the response. Then I feel the problem is the description of the HELP. Perhaps someting like this will be more descriptive:
```
-A --virtual-diseqc mapping_string: absolute source mapping for virtual diseqc mode

   The format is: SRC1:ADAP1:DISEQC1[,SRC2:ADAP2:DISEQC2]
   SRC: satellite position requested by clients (src argument for SAT>IP request minus 1, range: 0-63) (MAX_ADAPTERS 64)
   ADAP: internal adapter (see -a and -e) (range: 0-63) (MAX_SOURCES 64)
   DISEQC: target diseqc position of the adapter (range: 0-15) (or more if your adapter supports it) 
```

If you agree then I'll provide a PR.
And please, comment if you agree with a reordering of the options in the HELP too. I prefer an alphabetical order than the current unshorted list.

Regarding the question of
> In the current situation how do u see * working ? Pass all src from 1-32 or 64 ? -A 0:0:* would translate to 0:0:0, 1:0:1 , ... 31:0:31 ?

What I want to describe is that the target adapter (ADAP, second parameter in the mapping_string) will receive all SRC as DISEQC. So no mapping is required. However, perhaps with the current syntax this will be quite complex. Perhaps using ranges and the "*" symbol then it will be more easy. Example: `0-3:0:0-3,0-3:1:0-3,4-7:2:0-3,*:3:*`.
In this case: adapters 0 and 1 are "connected" to sources 0-3 without mapping; adapter 2 is connected to sources 4-7 with a mapping to regular diseqc (0-3); and the last adapter 3 is connected to the 8 positions and receives them untouched.
What you think about this idea? It's a simple reduction of the current syntax. With an expansion it translates to `0:0:0,1:0:1,...,3:0:3,0:1:0,...,3:1:3,4:2:0,5:2:1,...,7:2:3,0:3:0,...,7:3:7`. A lot of stuff to write!!

Regards.

**Comment by catalinii** [comment]
1) I have update the description
2) Feel free to create a PR to re=order alphabetically the options
3) I think rage makes sense, but don't understand how to use *. If we use range I think * can be implmented easily using range, would you agree ?

**Comment by odehalaa** [comment]
many thanks for your kindly support and amazing new feature :)

**Comment by Jalle19** [comment]
So, if I previously would have used `-U 0-2:3` to specify that `src=1` is available on adapter 0, 1 and 2 while `src=2` is available on adapter 3, how would I go about configuring that with the new `-A` switch?

**Comment by catalinii** [comment]
-A 0:0:0,0:1:0,0:2:0,1:3:1
I can see only -U 0-2:3 but that does not translate to 
`src=1 is available on adapter 0, 1 and 2 while src=2 is available on adapter 3,`

**Comment by Jalle19** [comment]
Yes it does, the format is pos1:pos3:pos3 etc. So the first src/pos is available on adapters 0-2, and src/pos is available on adapter 3.

Isn't this the correct usage? At least it seems to work 🤔🤷
