### ISSUE TITLE
windows porting : can I make it?

### ISSUE THREAD

**Issue by franalta** [catalinii/minisatip#957]
Hi to all, I'm not familiar with github repository, I want know on what ansi c standard is written the service, if I can make a wrapper to porting it to windows (both x86 than x64) and what compiler and how compile it... hope that somebody help me

p.s. satip standard does it support dvb-s2x ?

**Comment by Jalle19** [comment]
To be honest, it's not worth it

**Comment by franalta** [comment]
> 

why?

**Comment by 9000h** [comment]
what would be the benefit, to waste a windows license which is more expensive as complete hardware SAT>IP server like the Digibit R1.

**Comment by franalta** [comment]
feedback?

**Comment by Jalle19** [comment]
Seeing as the only thing that works if you don't run this on Linux is the SAT>IP client part you could just as well run minisatip in Docker or a virtual machine if all you have is a Windows host. It's simply not worth the effort to port this to Windows since it uses POSIX threads and many other "unixisms".

**Comment by Jalle19** [comment]
> p.s. satip standard does it support dvb-s2x ?

Yes, as far as I know at least.

**Comment by 9000h** [comment]
But you need to find a channel in dvbS2x, as fracas I know nothing on Astra 19.2 and Hotbird 13.0
