### ISSUE TITLE
refactoring core service as a driver

### ISSUE THREAD

**Issue by franalta** [catalinii/minisatip#958]
Hi, I'm been asking it's possible convert the source code of core as driver to increase performance and efficiency... what do you think? it's require many efforts?

**Comment by franalta** [comment]
nobody?

**Comment by Jalle19** [comment]
I have a feeling you don't really know what you're asking for? As far as I know there aren't any performance issues, and even if there were it would probably not make sense to move anything to kernel-space.

**Comment by franalta** [comment]
yes, there aren't performance issues, my opinion is that get data from driver tuner and convert it it's however more efficient... if I will have enough knowledge I'll try to make this porting with a fork

**Comment by catalinii** [comment]
I would not bother with it. I think for satip axe which is a very slow cpu, minisatip can still push very high bw because of the fact that the input buffer is used for output and multiple packets are chained together in 1 syscall.

The real bottleneck could be decrypting but doing that on the kernel side will not help much from decrypting perspective.

Not sure what is your use case but never saw minisatip without decryption going over few percentages on modern cpus.

**Comment by franalta** [comment]
question is: if I can make it more efficient, why not make it?

**Comment by catalinii** [comment]
Think about it this way:
What do you gain from it?
- if your server will use 5% cpu instead of 10% and now is 95% idle instead of 90% ... You still pay the costs of the server.

What is your use case?

**Comment by franalta** [comment]
whay standard ANSI C has been used to develop the server?

**Comment by catalinii** [comment]
Now it compiles even with C99
