### ISSUE TITLE
HDHomeRun using minisatip under Unbuntu 22.04

### ISSUE THREAD

**Issue by retrofan1979** [catalinii/minisatip#972]
Hi, does minisatip support a signal from a HDHomeRun device as input and if so, how to set up?
I don't get it work and I already installed the following libraries on Ubuntu 22.04.

sudo apt-get install hdhomerun-config hdhomerun-config-gui

Or do I miss something?

**Comment by lars18th** [comment]
Hi @retrofan1979 ,

> I hope minisatip will support the HDHomeRun devices very soon.

I believe it will be several years before the `hdhrc` module will be developed. No one is now interested on it.

Regarding the option 3: Yes I'm using SATPI. But it's a very complex install. I use a lightweight streaming server that can read the entire transport stream with the `hdhomerun_config` tool. This tool is managed by a custom own script build with shell script. Then the SATPI server is configured to read from this streaming server using the PIPE input when a specific frequency is requested. So from the point of view of the minisatip the SATPI is a regular SAT>IP server with internal filtering support. Quite complex but it works like a charm.

And regarding the option 2 the problem is that the Linux DVB drivers I feel are very old and only compatible with x86. So you're out of luck if you want to run them in a Raspberry Pi or a STB.

Regards.

**Comment by retrofan1979** [comment]
Hi! Fun to read! And great it works for you.
Too bad there are no recent Linux DVB drivers.
I'll stick with option 1 which is good enough for me for now.
I close this topic.
